"""
LendSure synthetic dataset generator — 1,500 borrowers x 51 INPUT features.
Seeded RNG: identical output on every run (no random drift between demos).
Outputs: data/borrowers.csv, data/financials.csv, data/documents.csv
INPUTS ONLY — no risk/fraud/trust/recommendation labels (generated by engines).
Run: python data_gen.py
"""
import csv
import math
import random
from pathlib import Path

SEED = 42
N = 1500
OUT = Path(__file__).parent / "data"

FIRST = ["Aarav", "Vihaan", "Arjun", "Sai", "Reyansh", "Krishna", "Ishaan", "Rohan", "Kabir", "Ananya",
         "Diya", "Aadhya", "Myra", "Sara", "Ira", "Priya", "Rahul", "Sneha", "Amit", "Pooja",
         "Vikram", "Neha", "Sanjay", "Kavya", "Manoj", "Divya", "Kiran", "Anil", "Meera", "Ravi",
         "Sunita", "Rajesh", "Lakshmi", "Deepak", "Anita", "Suresh", "Kavitha", "Arun", "Geeta", "Nikhil"]
LAST = ["Sharma", "Verma", "Patel", "Iyer", "Reddy", "Khan", "Gupta", "Mehta", "Nair", "Das",
        "Kulkarni", "Joshi", "Agarwal", "Singh", "Yadav", "Mishra", "Pillai", "Rao", "Chopra", "Bose"]
CITIES = [("Mumbai", 16), ("Delhi", 14), ("Bengaluru", 12), ("Pune", 9), ("Hyderabad", 9),
          ("Chennai", 8), ("Kolkata", 7), ("Ahmedabad", 6), ("Jaipur", 5), ("Lucknow", 4),
          ("Kochi", 3), ("Indore", 3), ("Nagpur", 2), ("Surat", 2)]
EMP = ["salaried", "self-employed", "business", "daily-wage"]
PURPOSES = ["personal", "business", "medical", "education", "home-repair"]
DOC_TYPES = ["identity", "bank_statement", "income_document", "salary_slip", "business_document"]

# 51 input features, grouped (order = CSV column order after id/name)
FEATURES = [
    # profile (7)
    "age", "city", "employment_type", "employment_years", "monthly_income", "household_size", "dependents",
    # loan request (4)
    "requested_amount", "tenure_months", "purpose", "first_time_borrower",
    # repayment history (6)
    "prev_loans", "loans_repaid", "late_payments", "avg_delay_days", "defaults", "max_days_past_due",
    # six-month financials (9)
    "avg_income_6m", "avg_expenses_6m", "avg_debt_6m", "income_volatility", "expense_trend", "debt_trend",
    "total_transactions_6m", "bounced_payments_6m", "disputed_txns_6m",
    # verification (6)
    "id_verification", "address_verification", "phone_verification",
    "bank_stmt_status", "income_doc_status", "doc_quality_score",
    # behavior (6)
    "transaction_variance", "night_txn_ratio", "new_device_90d", "applications_30d",
    "address_changes_12m", "doc_avg_income",
    # trust network (5)
    "vouches_count", "avg_vouch_trust", "community_tenure_years", "group_memberships", "guarantor_past_count",
    # account history (8)
    "account_age_months", "prev_lenders_count", "disputes_raised", "disputes_lost",
    "ontime_streak_months", "salary_credits_6m", "savings_balance", "existing_debt_accounts",
]
assert len(FEATURES) == 51, len(FEATURES)


def wpick(rng, weighted):
    total = sum(w for _, w in weighted)
    x = rng.random() * total
    for v, w in weighted:
        x -= w
        if x <= 0:
            return v
    return weighted[-1][0]


def slope(xs):
    n = len(xs)
    mx = sum(range(n)) / n
    my = sum(xs) / n
    den = sum((i - mx) ** 2 for i in range(n)) or 1
    return sum((i - mx) * (v - my) for i, v in enumerate(xs)) / den


def gen_borrower(rng, i):
    bid = f"B{10001 + i}"
    arch = rng.choices(["prime", "stable", "stretched", "thin", "risky"], [22, 33, 20, 15, 10])[0]

    age = max(19, min(68, int(rng.gauss(36, 10))))
    city = wpick(rng, CITIES)
    employment_type = rng.choices(EMP, [38, 32, 14, 16])[0] if arch != "thin" else rng.choices(EMP, [20, 30, 10, 40])[0]

    if arch == "prime":
        income = int(rng.gauss(75000, 18000)); emp_y = round(rng.uniform(3, 15), 1)
        prev, repaid, late, defs = rng.randint(2, 8), 0, rng.randint(0, 1), 0
    elif arch == "stable":
        income = int(rng.gauss(45000, 12000)); emp_y = round(rng.uniform(1.5, 8), 1)
        prev, repaid, late, defs = rng.randint(1, 6), 0, rng.randint(0, 2), 0
    elif arch == "stretched":
        income = int(rng.gauss(35000, 10000)); emp_y = round(rng.uniform(1, 6), 1)
        prev, repaid, late, defs = rng.randint(1, 5), 0, rng.randint(1, 4), rng.choices([0, 1], [80, 20])[0]
    elif arch == "thin":
        income = int(rng.gauss(22000, 8000)); emp_y = round(rng.uniform(0, 2), 1)
        prev, repaid, late, defs = rng.randint(0, 1), 0, 0, 0
    else:
        income = int(rng.gauss(28000, 12000)); emp_y = round(rng.uniform(0, 3), 1)
        prev, repaid, late, defs = rng.randint(1, 6), 0, rng.randint(2, 6), rng.randint(1, 3)
    income = max(8000, income)
    repaid = max(0, min(prev, prev - defs - (1 if late > 3 else 0)))
    avg_delay = round(rng.uniform(0, 5) if late == 0 else rng.uniform(4, 30), 1)
    max_dpd = 0 if late == 0 else int(rng.uniform(5, 60))
    first_time = 1 if prev == 0 else 0

    mult = rng.uniform(1.5, 4) if arch in ("prime", "stable") else rng.uniform(2, 9)
    requested = int(min(500000, max(10000, income * mult)) // 1000 * 1000)
    tenure = rng.choices([3, 6, 12, 18, 24], [15, 25, 35, 15, 10])[0]
    purpose = rng.choice(PURPOSES)

    # 6-month series (income, expenses, debt, txns, bounced, disputed)
    drift = rng.uniform(-0.06, 0.09) if arch != "risky" else rng.uniform(-0.02, 0.22)
    base_inc = income * rng.uniform(0.92, 1.05)
    months = []
    for m in range(6):
        mi = max(4000, base_inc * (1 + drift * (m - 2.5) / 2.5) * rng.uniform(0.9, 1.1))
        me = mi * rng.uniform(0.45, 0.8 if arch in ("prime", "stable") else 0.95)
        md = income * rng.uniform(0.1, 0.5 if arch in ("prime", "stable") else 1.4)
        mt = int(rng.uniform(25, 90))
        months.append((round(mi), round(me), round(md), mt))
    avg_inc = sum(m[0] for m in months) / 6
    avg_exp = sum(m[1] for m in months) / 6
    avg_debt = sum(m[2] for m in months) / 6
    var = (sum((m[0] - avg_inc) ** 2 for m in months) / 6) ** 0.5 / (avg_inc or 1)
    txn_mean = sum(m[3] for m in months) / 6
    txn_var = (sum((m[3] - txn_mean) ** 2 for m in months) / 6) ** 0.5 / (txn_mean or 1)
    bounced = sum(1 for _ in range(6) for _ in [0] if rng.random() < (0.02 if arch in ("prime", "stable") else 0.16))
    disputed = sum(1 for _ in range(6) if rng.random() < (0.01 if arch in ("prime", "stable") else 0.1))

    def vstat(p_verified, p_pending=15):
        x = rng.random() * 100
        return 2 if x < p_verified else (1 if x < p_verified + p_pending else 0)
    pv = {"prime": 95, "stable": 85, "stretched": 70, "thin": 55, "risky": 45}[arch]
    id_v, addr_v, ph_v = vstat(pv), vstat(pv - 8), vstat(pv - 3)
    bank_st = vstat(pv, 12) if arch != "risky" else rng.choices([0, 1, 2], [30, 35, 35])[0]
    inc_st = vstat(pv - 5, 18)
    doc_q = int(max(20, min(99, rng.gauss(88 if arch == "prime" else 72 if arch == "stable" else 58, 12))))
    doc_avg_inc = round(avg_inc * rng.uniform(0.85, 1.1) if arch != "risky" else avg_inc * rng.uniform(0.5, 1.5))

    night = round(rng.uniform(0.02, 0.12 if arch in ("prime", "stable") else 0.3), 3)
    new_dev = 1 if rng.random() < (0.05 if arch != "risky" else 0.3) else 0
    vel = rng.choices([1, 2, 3, 4], [70, 18, 8, 4])[0] if arch != "risky" else rng.choices([1, 2, 3, 5], [40, 25, 20, 15])[0]
    addr_ch = rng.choices([0, 1, 2], [80, 15, 5])[0]

    vouches = rng.randint(2, 6) if arch in ("prime", "stable") else rng.randint(0, 3)
    vouch_trust = round(rng.uniform(3.5, 5) if vouches else 0, 1)
    comm_ten = round(rng.uniform(1, 12), 1)
    groups = rng.randint(0, 4)
    guarantor = rng.randint(0, 3) if arch in ("prime", "stable") else rng.randint(0, 1)

    acct_age = int(rng.uniform(12, 120))
    prev_lenders = rng.randint(0, 4)
    disp_r = rng.randint(0, 3) if arch == "risky" else rng.randint(0, 1)
    disp_l = rng.randint(0, disp_r)
    streak = int(rng.uniform(6, 36) if arch in ("prime", "stable") else rng.uniform(0, 10))
    sal_cred = 6 if employment_type == "salaried" and arch != "risky" else rng.randint(0, 5)
    savings = int(max(0, rng.gauss(income * (3 if arch == "prime" else 1.2), income)))
    debt_accts = rng.randint(0, 2) if arch in ("prime", "stable") else rng.randint(0, 5)

    row = {
        "borrower_id": bid,
        "name": f"{rng.choice(FIRST)} {rng.choice(LAST)}",
        "age": age, "city": city, "employment_type": employment_type, "employment_years": emp_y,
        "monthly_income": income, "household_size": rng.randint(1, 6), "dependents": rng.randint(0, 4),
        "requested_amount": requested, "tenure_months": tenure, "purpose": purpose,
        "first_time_borrower": first_time,
        "prev_loans": prev, "loans_repaid": repaid, "late_payments": late, "avg_delay_days": avg_delay,
        "defaults": defs, "max_days_past_due": max_dpd,
        "avg_income_6m": round(avg_inc), "avg_expenses_6m": round(avg_exp),
        "avg_debt_6m": round(avg_debt), "income_volatility": round(var, 3),
        "expense_trend": round(slope([m[1] for m in months]) / (avg_exp or 1), 4),
        "debt_trend": round(slope([m[2] for m in months]) / (avg_debt or 1), 4),
        "total_transactions_6m": sum(m[3] for m in months),
        "bounced_payments_6m": bounced, "disputed_txns_6m": disputed,
        "id_verification": id_v, "address_verification": addr_v, "phone_verification": ph_v,
        "bank_stmt_status": bank_st, "income_doc_status": inc_st, "doc_quality_score": doc_q,
        "transaction_variance": round(txn_var, 3), "night_txn_ratio": night, "new_device_90d": new_dev,
        "applications_30d": vel, "address_changes_12m": addr_ch, "doc_avg_income": doc_avg_inc,
        "vouches_count": vouches, "avg_vouch_trust": vouch_trust, "community_tenure_years": comm_ten,
        "group_memberships": groups, "guarantor_past_count": guarantor,
        "account_age_months": acct_age, "prev_lenders_count": prev_lenders,
        "disputes_raised": disp_r, "disputes_lost": disp_l, "ontime_streak_months": streak,
        "salary_credits_6m": sal_cred, "savings_balance": savings, "existing_debt_accounts": debt_accts,
    }
    return row, months


def main():
    OUT.mkdir(exist_ok=True)
    rng = random.Random(SEED)
    with open(OUT / "borrowers.csv", "w", newline="") as f, \
         open(OUT / "financials.csv", "w", newline="") as ff, \
         open(OUT / "documents.csv", "w", newline="") as df:
        bw = csv.DictWriter(f, fieldnames=["borrower_id", "name"] + FEATURES)
        bw.writeheader()
        fw = csv.writer(ff)
        fw.writerow(["borrower_id", "month", "label", "income", "expenses", "debt", "transactions", "bounced", "disputed"])
        dw = csv.writer(df)
        dw.writerow(["borrower_id", "doc_type", "file_name", "status", "quality_score", "note"])
        labels = ["M-6", "M-5", "M-4", "M-3", "M-2", "M-1"]
        for i in range(N):
            row, months = gen_borrower(rng, i)
            bw.writerow(row)
            for m, vals in enumerate(months):
                mi, me, md, mt = vals
                fw.writerow([row["borrower_id"], m, labels[m], mi, me, md, mt,
                             1 if (m * 7 + i) % 41 == 0 and row["bounced_payments_6m"] else 0,
                             1 if (m * 5 + i) % 67 == 0 and row["disputed_txns_6m"] else 0])
            ver_map = {2: "verified", 1: "needs_review", 0: "suspicious"}
            doc_rows = [
                ("identity", ver_map[row["id_verification"]]),
                ("bank_statement", ver_map[row["bank_stmt_status"]]),
                ("income_document", ver_map[row["income_doc_status"]]),
            ]
            if row["employment_type"] == "salaried":
                doc_rows.append(("salary_slip", ver_map[row["income_doc_status"]]))
            if row["employment_type"] in ("business", "self-employed") and rng.random() < 0.5:
                doc_rows.append(("business_document", ver_map[row["bank_stmt_status"]]))
            for dt, st in doc_rows:
                q = max(15, min(99, row["doc_quality_score"] + rng.randint(-12, 8)))
                dw.writerow([row["borrower_id"], dt,
                             f"{row['borrower_id'].lower()}_{dt}.pdf", st, q,
                             "OCR pending — status from structured verification" if st != "verified" else "Structured checks passed"])
    print(f"Wrote {N} borrowers x {len(FEATURES)} features to {OUT}/")


if __name__ == "__main__":
    main()
